sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.182.128
    port: 3306
    database: sky_take_out
    username: root
    password: "000000"

  minio:
    access-key: sTWGmBUUlcMH1eEfls8s
    secret-key: Nws5v4V1BJiNP51Dt2ThVKsHOHWbjMOpAOJrYjbK
    url: http://192.168.182.128:9000
    bucket-name: public

  redis:
    host: 192.168.182.128
    port: 6379
    password: "000000"
    database: 1
